DROP TABLE IF EXISTS base CASCADE ;
DROP TABLE IF EXISTS galaxy CASCADE;
DROP TABLE IF EXISTS licence CASCADE ;
DROP TABLE IF EXISTS mission CASCADE ;
DROP TABLE IF EXISTS on_base CASCADE ;
DROP TABLE IF EXISTS on_mission CASCADE ;
DROP TABLE IF EXISTS pilot CASCADE ;
DROP TABLE IF EXISTS planet CASCADE ;
DROP TABLE IF EXISTS spaceship CASCADE ;